language: node_js
node_js:
  - 6
  - 8
  - 9
  - 10
before_script:
  - 'mkdir coverage'
  - 'npm run build'
script:
  - 'npm run test:example'
  - 'npm run test:ci'
after_script:
  - 'npm run codecov'
notifications:
  email: false
